// bannerInit.js - initialize Banners for menus
import { mkbanner } from "./sharedHelpers/banner.js"
import { vars } from "./vars.js"

function bannerInit() {
  document.getElementById("vocbanner").innerText = mkbanner("TinyVoc v" + vars.version, 45, "-")

  document.getElementById("statusheader").innerText = mkbanner("Git Status", 45, "-")
  document.getElementById("configurationheader").innerText = mkbanner("Configuration", 45, "-")
  document.getElementById("correctbanner").innerText = mkbanner("Correct vocabulary", 45, "-")
  document.getElementById("statsbanner").innerText = mkbanner("Training Statistics", 45, "=")
  document.getElementById("addbanner").innerText = mkbanner("Add vocabulary", 45, "-")
  document.getElementById("trainbanner").innerText = mkbanner("Train vocabulary", 45, "-")
  document.getElementById("viewbanner").innerText = mkbanner("View vocabulary", 45, "-")
  document.getElementById("printfooter").innerText = mkbanner("Generated by TinyVoc", 50, "-")
  document.getElementById("generateheader").innerText = mkbanner("Generate List", 45, "-")
  document.getElementById("trainfooter").innerText = mkbanner("0/0", 45, "-")
  document.getElementById("lectionviewheader").innerText = mkbanner("Lection View", 45, "-")
  document.getElementById("moveheader").innerText = mkbanner("Move List", 45, "-")
  document.getElementById("joinheader").innerText = mkbanner("Join Lections", 45, "-")
  document.getElementById("broadcastheader").innerText = mkbanner("Broadcast", 45, "-")
  document.getElementById("githeader").innerText = mkbanner("Git", 45, "-")
  document.getElementById("docsheader").innerText = mkbanner("TinyVoc Docs", 45, "-")
  document.getElementById("figureheader").innerText = mkbanner("Figure View", 45, "-")
  document.getElementById("configurationfooter").innerText = mkbanner("", 45, "-")
  document.getElementById("statsfooter").innerText = mkbanner("", 45, "=")
  document.getElementById("movefooter").innerText = mkbanner("", 45, "-")
  document.getElementById("correctfooter").innerText = mkbanner("", 45, "-")
  document.getElementById("vocfooter").innerText = mkbanner("", 45, "-")
  document.getElementById("statusfooter").innerText = mkbanner("", 45, "-")
  document.getElementById("addfooter").innerText = mkbanner("", 45, "-")
  document.getElementById("viewfooter").innerText = mkbanner("", 45, "-")
  document.getElementById("generatefooter").innerText = mkbanner("", 45, "-")
  document.getElementById("docsfooter").innerText = mkbanner("", 45, "-")
  document.getElementById("lectionviewfooter").innerText = mkbanner("", 45, "-")
  document.getElementById("broadcastfooter").innerText = mkbanner("", 45, "-")
  document.getElementById("figurefooter").innerText = mkbanner("", 45, "-")
  document.getElementById("gitfooter").innerText = mkbanner("", 45, "-")
  document.getElementById("joinfooter").innerText = mkbanner("", 45, "-")
}

export { bannerInit }
